title: Alessandro Roic
description: >-
  Personal website built with Angular, designed and developed to showcase my skills and latest projects
url : https://alessandroroic.github.io
baseurl: /alessandroroic-v1.0.github.io
github_username:  AlessandroRoic

